name: Build PyGeopack In Container

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to use in container'
        required: false
        default: '3.14'

run-name: ${{ github.event_name == 'workflow_dispatch' && 'Build PyGeopack In Container' || 'Monthly Build' }}

env:
  CONTAINER_NAME: pygeopack-build-container
  IMAGE_NAME: pygeopack-build-image
  PYTHON_VERSION: ${{ inputs.python-version || '3.14' }}

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build container image
        run: |
          cd tools
          docker build -t $IMAGE_NAME --build-arg PYTHON_VERSION=$PYTHON_VERSION .

      - name: Create and start container
        run: |
          docker run -d --name $CONTAINER_NAME $IMAGE_NAME

      - name: Build PyGeopack in container
        run: |
          bash ./tools/container-build.sh $CONTAINER_NAME

      - name: Stop and remove container
        if: always()
        run: |
          docker stop $CONTAINER_NAME || true
